#[derive(Deserialize, Serialize, Default, Clone, Debug)]
pub struct Toml {
    pub start: Option<StartData>,
    pub Sectors: Option<Vec<SectorData>>,
    pub Ships: Option<Vec<ShipData>>,
    pub Stations: Option<Vec<StationData>>,
    pub Trade: Option<Vec<OfferData>>,
}
#[derive(Deserialize, Serialize, Default, Clone, Debug)]
pub struct StartData {
    pub _id: Option<String>,
    pub r#type: Option<String>,
    pub time: Option<f32>,
    pub deadships: Option<i32>,
    pub deadstations: Option<i32>,
    pub iteration: Option<i32>,
}
// #[derive(Deserialize, Serialize, Default, Clone, Debug)]
// pub struct FactionData {
//     pub Sectors: Option<Vec<SectorData>>,
//     pub Ships: Option<Vec<ShipData>>,
//     pub Stations: Option<Vec<StationData>>,
// }
#[derive(Deserialize, Serialize, Default, Clone, Debug)]
pub struct SectorData {
    pub _id: Option<String>,
    pub r#type: Option<String>,
    pub owner: Option<String>,
    pub sector: Option<String>,
    pub r#macro: Option<String>,
    pub iscontested: Option<bool>,
    pub averagedistancetolockbox: Option<f32>,
    pub typicallockboxmacro: Option<String>,
}
#[derive(Deserialize, Serialize, Default, Clone, Debug)]
pub struct ShipData {
    pub _id: Option<String>,
    pub r#type: Option<String>,
    pub owner: Option<String>,
    pub ship: Option<String>,
    pub r#macro: Option<String>,
    pub job: Option<String>,
    pub canbeclaimed: Option<bool>,
    pub issupplyship: Option<bool>,
    pub iscapitalship: Option<bool>,
    pub averageprice: Option<i32>,
    pub sector: Option<String>,
    pub trueowner: Option<String>,
    pub isdeployedconstructionvessel: Option<bool>,
    pub isknown: Option<bool>,
    pub hullpercentage: Option<f32>,
    pub shieldpercentage: Option<f32>,
    pub maxhull: Option<f32>,
    pub maxshield: Option<f32>,
    pub isformationleader: Option<bool>,
    pub value: Option<i64>,
    pub order: Option<String>,
    pub primarypurpose: Option<String>,
    pub pilot: Option<String>,
    pub boarding: Option<i32>,
    pub engineering: Option<i32>,
    pub management: Option<i32>,
    pub morale: Option<i32>,
    pub piloting: Option<i32>,
    // pub advancedcomposites: Option<i32>,
    // pub advancedelectronics: Option<i32>,
    // pub antimattercells: Option<i32>,
    // pub antimatterconverters: Option<i32>,
    // pub claytronics: Option<i32>,
    // pub dronecomponents: Option<i32>,
    // pub energycells: Option<i32>,
    // pub engineparts: Option<i32>,
    // pub fieldcoils: Option<i32>,
    // pub foodrations: Option<i32>,
    // pub graphene: Option<i32>,
    // pub helium: Option<i32>,
    // pub hullparts: Option<i32>,
    // pub hydrogen: Option<i32>,
    // pub ice: Option<i32>,
    // pub majadust: Option<i32>,
    // pub majasnails: Option<i32>,
    // pub meat: Option<i32>,
    // pub medicalsupplies: Option<i32>,
    // pub methane: Option<i32>,
    // pub microchips: Option<i32>,
    // pub missilecomponents: Option<i32>,
    // pub nividium: Option<i32>,
    // pub nostropoil: Option<i32>,
    // pub ore: Option<i32>,
    // pub plasmaconductors: Option<i32>,
    // pub quantumtubes: Option<i32>,
    // pub refinedmetals: Option<i32>,
    // pub scanningarrays: Option<i32>,
    // pub shieldcomponents: Option<i32>,
    // pub silicon: Option<i32>,
    // pub siliconwafers: Option<i32>,
    // pub smartchips: Option<i32>,
    // pub sojabeans: Option<i32>,
    // pub sojahusk: Option<i32>,
    // pub spacefuel: Option<i32>,
    // pub spaceweed: Option<i32>,
    // pub spices: Option<i32>,
    // pub sunriseflowers: Option<i32>,
    // pub superfluidcoolant: Option<i32>,
    // pub swampplant: Option<i32>,
    // pub teladianium: Option<i32>,
    // pub turretcomponents: Option<i32>,
    // pub water: Option<i32>,
    // pub weaponcomponents: Option<i32>,
    // pub wheat: Option<i32>,
    pub wares: Option<Vec<(String, i32)>>,
}
#[derive(Deserialize, Serialize, Default, Clone, Debug)]
pub struct StationData {
    pub _id: Option<String>,
    pub r#type: Option<String>,
    pub owner: Option<String>,
    pub station: Option<String>,
    pub sector: Option<String>,
    pub istradestation: Option<bool>,
    pub isshipyard: Option<bool>,
    pub iswharf: Option<bool>,
    pub isequipmentdock: Option<bool>,
    pub isdefencestation: Option<bool>,
    pub ispiratebase: Option<bool>,
    pub isheadquarters: Option<bool>,
    pub isfactionheadquarters: Option<bool>,
    pub isplannedshipyard: Option<bool>,
    pub isplannedwharf: Option<bool>,
    pub isplannedequipmentdock: Option<bool>,
    pub isplanneddefencestation: Option<bool>,
    // pub advancedcomposites: Option<Vec<i32>>,
    // pub advancedelectronics: Option<Vec<i32>>,
    // pub antimattercells: Option<Vec<i32>>,
    // pub antimatterconverters: Option<Vec<i32>>,
    // pub claytronics: Option<Vec<i32>>,
    // pub dronecomponents: Option<Vec<i32>>,
    // pub energycells: Option<Vec<i32>>,
    // pub engineparts: Option<Vec<i32>>,
    // pub fieldcoils: Option<Vec<i32>>,
    // pub foodrations: Option<Vec<i32>>,
    // pub graphene: Option<Vec<i32>>,
    // pub helium: Option<Vec<i32>>,
    // pub hullparts: Option<Vec<i32>>,
    // pub hydrogen: Option<Vec<i32>>,
    // pub ice: Option<Vec<i32>>,
    // pub majadust: Option<Vec<i32>>,
    // pub majasnails: Option<Vec<i32>>,
    // pub meat: Option<Vec<i32>>,
    // pub medicalsupplies: Option<Vec<i32>>,
    // pub methane: Option<Vec<i32>>,
    // pub microchips: Option<Vec<i32>>,
    // pub missilecomponents: Option<Vec<i32>>,
    // pub nividium: Option<Vec<i32>>,
    // pub nostropoil: Option<Vec<i32>>,
    // pub ore: Option<Vec<i32>>,
    // pub plasmaconductors: Option<Vec<i32>>,
    // pub quantumtubes: Option<Vec<i32>>,
    // pub refinedmetals: Option<Vec<i32>>,
    // pub scanningarrays: Option<Vec<i32>>,
    // pub shieldcomponents: Option<Vec<i32>>,
    // pub silicon: Option<Vec<i32>>,
    // pub siliconwafers: Option<Vec<i32>>,
    // pub smartchips: Option<Vec<i32>>,
    // pub sojabeans: Option<Vec<i32>>,
    // pub sojahusk: Option<Vec<i32>>,
    // pub spacefuel: Option<Vec<i32>>,
    // pub spaceweed: Option<Vec<i32>>,
    // pub spices: Option<Vec<i32>>,
    // pub sunriseflowers: Option<Vec<i32>>,
    // pub superfluidcoolant: Option<Vec<i32>>,
    // pub swampplant: Option<Vec<i32>>,
    // pub teladianium: Option<Vec<i32>>,
    // pub turretcomponents: Option<Vec<i32>>,
    // pub water: Option<Vec<i32>>,
    // pub weaponcomponents: Option<Vec<i32>>,
    // pub wheat: Option<Vec<i32>>,
    pub wares: Option<Vec<(String, i32, i32)>>,
    pub modules: Option<Vec<String>>,
}
#[derive(Deserialize, Serialize, Default, Clone, Debug)]
pub struct OfferData {
    pub _id: Option<String>,
    pub r#type: Option<String>,
    pub offer: Option<String>,
    pub buyer: Option<String>,
    pub seller: Option<String>,
    pub owner: Option<String>,
    pub ware: Option<String>,
    pub amount: Option<i32>,
    pub desiredamount: Option<i32>,
    pub offeramount: Option<i32>,
    pub minamount: Option<i32>,
    pub transferredamount: Option<i32>,
    pub destroyedamount: Option<i32>,
    pub volume: Option<i32>,
    pub price: Option<i64>,
    pub unitprice: Option<i32>,
    pub iswareexchange: Option<bool>,
    pub isshiptoship: Option<bool>,
    pub isbuyerpassive: Option<bool>,
    pub issellerpassive: Option<bool>,
}
